name: sgdm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip=20.3
  - pip:
    - opencv-python
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning
    - omegaconf==2.1.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.3.1
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
