MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  WEIGHTS: "data/dino_RN50_pretrain_d2_format.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "SyncBN"
  ROI_HEADS:
    NAME: "Res5ROIHeadsExtraNorm"
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.01
    NMS_THRESH_TEST: 0.4
  BACKBONE:
    FREEZE_AT: 2
  ROI_BOX_HEAD:
    NORM: "SyncBN" # RGB Mean and Std
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  FORMAT: "RGB"
DATASETS:
  TRAIN: ('coco20k_train_LOST_CAD', )
  TEST: ('coco20k_train_CAD_gt', )
TEST:
  EVAL_PERIOD: 5000
  PRECISE_BN:
    ENABLED: True
SOLVER:
  STEPS: (18000, 22000)
  MAX_ITER: 24000
  WARMUP_ITERS: 100 # Maybe needs tuning.
  IMS_PER_BATCH: 16
  BASE_LR: 0.02 # Maybe it will need some tuning. MoCo used 0.02.
OUTPUT_DIR: "./outputs/RN50_DINO_FRCNN_COCO20k_CAD"