name: adam
params:
  lr: ${data.lr}
  eps: 1e-8
  beta1: 0.9
  beta2: 0.99
  wd: ${data.wd} #wd: 0.0

scheduler_config: # 10000 warmup steps
    target: diffusion_utils.lr_scheduler.LambdaLinearScheduler
    params:
      warm_up_steps: [ 500 ]
      cycle_lengths: [ 10000000000000 ]
      f_start: [ 1.e-6 ]
      f_max: [ 1. ]
      f_min: [ 1. ]