name: adamw
params:
  lr: ${data.lr}
  wd: ${data.wd}

scheduler_config: # 10000 warmup steps
    target: diffusion_utils.lr_scheduler.LambdaLinearScheduler
    params:
      warm_up_steps: [ 500 ]
      cycle_lengths: [ 10000000000000 ]
      f_start: [ 1.e-6 ]
      f_max: [ 1. ]
      f_min: [ 1. ]