target: dynamic.diffusionmodules.openaimodel.UNetModel
params:
  image_size: ${data.image_size}
  in_channels: ${data.channels}
  out_channels: ${data.channels}
  dropout: 0.1
  model_channels: 128
  attention_resolutions: [2, 4]   # 8, 4
  num_res_blocks: 2
  channel_mult: [ 1,2,4]  # 32, 16, 8, 4, 2
  num_heads: 32
  use_scale_shift_norm: True
  resblock_updown: True
  cond_dim: ${sg.params.cond_dim}
  num_classes: ${data.num_classes}
  condition_method: ${sg.params.condition_method}
  cond_mlp_divide: [ 1,2,4]
  use_checkpoint: False
  use_fp16: False
  ############  classifier-free