target: lightning_module.TaoDiffusion
params:
  diffusion_model: ${model}
  dynamic: ${dynamic}
  data: ${data}
  model: ${model.params}
  exp: ${exp}
  vis: ${vis}
  condition: ${condition}
  optim: ${optim}
#######################################################
  device: cuda

  parameterization: eps #eps or x0

  use_ema: true
  debug: ${debug}
  log_dir: ${log_dir}
  profile: ${profile}

  
  condition_method: null #label, cluster, knn, labelcluster ,patchcluster, patchfeat, centroid, null
  cond_dim: null 
  cond_drop_prob: null # 0.1
  cond_scale: null #2.0


  ddim_eta: 0.0
  dtp: 1 #dynamic_thresholding_percentile, Imagen set it 0.9
  log_num_per_prog: 10
  ############evaluation related ############

  



