
image_dir: "/home/thu/data/coco14/train2014"
result_dir: "/home/thu/data/coco14_stego_generated_v0"
ckpt_path: "/home/thu/lab/self-guidance/side_repo/STEGO/saved_models/cocostuff27_vit_base_5.ckpt"
papervis_dir: '/home/thu/lab/self-guidance/side_repo/STEGO/outputs/papervis_stego_coco14'


num_workers: 8


is_vis: True
